---
- hosts: all
  vars:
    sites:
      - server_name: google.com
        name: google
        listen: 8080 default_server
        index: "index.php index.html index.htm"
        root: "/var/www/html"
      - server_name: yandex.ru
        name: yandex
        listen: 8888 default_server
        index: "index.php index.html index.htm"
        root: "/var/www/html"

    nginx_user: "www-data"
    nginx_pidfile: "/run/nginx.pid"
    nginx_modules: "/etc/nginx/modules-enabled/*.conf"
    nginx_worker_connections: "768"
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"
    nginx_keepalive_timeout: "65"
    nginx_mime_file_path: "/etc/nginx/mime.types"
    nginx_types_hash_max_size: "2048"

  become: yes
  tasks:
  - name: Installs nginx web server
    apt:
      name: nginx=1.14.0-0ubuntu1.9
      state: present
      update_cache: true
    notify: start nginx

  - name: Write the vhosts config file
    template:
      src: "~/ansible/nginx.j2"
      dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    with_items: "{{ sites }}"
    notify: reload nginx

  - name: Write the nginx config file
    template:
      src: "~/ansible/nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
    notify: reload nginx

  handlers:
    - name: start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
