---
- hosts: all
  become: yes
  tasks:
    - name: Installs nginx web server
      apt:
        name: nginx
        state: latest
        update_cache: true
      notify: start nginx
  handlers:
    - name: start nginx
      systemd:
        name: nginx
        state: started
