---
inventory_hostname_u: brutalhz-u.devops.rebrain.srwx.net
inventory_hostname_c: brutalhz-c.devops.rebrain.srwx.net
certbot_auto_renew: true
certbot_admin_email: denis.iddqd@gmail.com
certbot_script: /usr/bin/certbot
certbot_output_dir: "/etc/letsencrypt/live/{{ inventory_hostname }}"
update_apt_cache: true
